.TH "SURFING_CLI" "1" "27-Sep-2018" "2.0" "surfing_cli Manual"
.SH NAME
surfing_cli \- 冲浪科技专用的命令脚本集 获取帮助: surfing_cli COMMAND --help
.SH SYNOPSIS
.B surfing_cli
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
冲浪科技专用的命令脚本集 
.PP
获取帮助: 
.PP
surfing_cli COMMAND --help
.SH COMMANDS
.PP
\fBpackage_assistant\fP
  命令：包助理。 用于：包分析，包清理等等
  See \fBsurfing_cli-package_assistant(1)\fP for full documentation on the \fBpackage_assistant\fP command.
.PP
\fBsrc_exist_on_dst_packages\fP
  获取目标中已经存在的源包列表
  See \fBsurfing_cli-src_exist_on_dst_packages(1)\fP for full documentation on the \fBsrc_exist_on_dst_packages\fP command.